# Generated by Django 5.1.4 on 2024-12-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="redactor",
            old_name="year_of_experience",
            new_name="years_of_experience",
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
