# Generated by Django 5.1.4 on 2024-12-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agency",
            "0002_rename_year_of_experience_redactor_years_of_experience_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
