# Generated by Django 5.1.5 on 2025-01-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0005_rename_topic_newspaper_topics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["username"],
                "verbose_name": "redactor",
                "verbose_name_plural": "redactors",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"]},
        ),
    ]
